---

- name: Install mysql server
  apt:
    name: mysql-server
    state: present
    update_cache: True

- name: Install required auxiliary apt packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: True
  with_items:
    - python-mysqldb

- name: Create mysql database for keystone
  mysql_db:
    name: "{{ keystone_db_name }}"
    state: present
  register: keystone_database

- name: Create mysql user for keystone
  mysql_user:
    name: "{{ keystone_db_user }}"
    host: '%'
    password: "{{ keystone_db_password }}"
    priv: '{{ keystone_db_name }}.*:ALL'
    state: present

- name: Install keystone (to bootstrap the database)
  apt:
    name: keystone
    state: present
    update_cache: True
  when: keystone_database is changed

- name: Configure keystone (to bootstrap the database)
  ini_file:
    path: /etc/keystone/keystone.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ keystone_configuration }}"

- name: Populate keystone database
  become_user: keystone
  command: keystone-manage db_sync
  when: keystone_database is changed

- name: Bootstrap keystone database
  become_user: keystone
  command: >
    keystone-manage bootstrap --bootstrap-password {{ keystone_bootstrap_password }}
    --bootstrap-admin-url {{ keystone_url }}:35357/v3/
    --bootstrap-internal-url {{ keystone_url }}:5000/v3/
    --bootstrap-public-url {{ keystone_url }}:5000/v3/
    --bootstrap-region-id {{ keystone_bootstrap_region }}
  when: keystone_database is changed

- name: Remove keystone
  apt:
    name: keystone
    state: absent
    autoclean: True
    autoremove: True
  when: keystone_database is changed

- name: Enable mysqld on all interfaces
  ini_file:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    section: mysqld
    option: bind-address
    value: 0.0.0.0
  notify: restart mysql
