---

platform: linux
image_resource:
  type: docker-image
  source:
    repository: imple/packer
inputs:
  - name: release
  - name: master
run:
  path: master/ci/scripts/build-image.sh
params:
  CI_COMPONENT: ((CI_COMPONENT))
  OS_AUTH_URL: ((OS_AUTH_URL))
  OS_DOMAIN_NAME: ((OS_DOMAIN_NAME))
  OS_ENDPOINT_TYPE: ((OS_ENDPOINT_TYPE))
  OS_IDENTITY_API_VERSION: ((OS_IDENTITY_API_VERSION))
  OS_INTERFACE: ((OS_INTERFACE))
  OS_PASSWORD: ((OS_PASSWORD))
  OS_PROJECT_ID: ((OS_PROJECT_ID))
  OS_PROJECT_NAME: ((OS_PROJECT_NAME))
  OS_REGION_NAME: ((OS_REGION_NAME))
  OS_USER_DOMAIN_NAME: ((OS_USER_DOMAIN_NAME))
  OS_USERNAME: ((OS_USERNAME))
  SSH_KEY: ((SSH_KEY))
