---

- name: restart consul
  service:
    name: consul
    state: restarted

- name: restart consul-template
  service:
    name: consul-template
    state: restarted

- name: reload systemd
  systemd: daemon_reload=yes