---

resources:
  - name: master
    type: git
    source:
      uri: https://github.com/rnurgaliyev/infra-automation-class.git
      branch: master

  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:rnurgaliyev/infra-automation-class.git
      branch: version
      file: version
      private_key: ((SSH_KEY))

  - name: release
    type: github-release
    source:
      owner: rnurgaliyev
      repository: infra-automation-class
      access_token: ((GITHUB_TOKEN))

jobs:
  - name: keystone
    plan:
    - get: master
      trigger: true
    - task: automation test
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: imple/ansible-kitchen
        inputs:
          - name: master
        run:
          path: master/ci/scripts/test/keystone.sh
        params:
          SSH_KEY: ((SSH_KEY))
          OS_AUTH_URL: ((OS_AUTH_URL))
          OS_IDENTITY_API_VERSION: ((OS_IDENTITY_API_VERSION))
          OS_PROJECT_ID: ((OS_PROJECT_ID))
          OS_USER_DOMAIN_NAME: ((OS_USER_DOMAIN_NAME))
          OS_INTERFACE: ((OS_INTERFACE))
          OS_ENDPOINT_TYPE: ((OS_ENDPOINT_TYPE))
          OS_USERNAME: ((OS_USERNAME))
          OS_PASSWORD: ((OS_PASSWORD))
          OS_REGION_NAME: ((OS_REGION_NAME))
          OS_PROJECT_NAME: ((OS_PROJECT_NAME))

  - name: keystone-db
    plan:
    - get: master
      trigger: true
    - task: automation test
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: imple/ansible-kitchen
        inputs:
          - name: master
        run:
          path: master/ci/scripts/test/keystone-db.sh
        params:
          SSH_KEY: ((SSH_KEY))
          OS_AUTH_URL: ((OS_AUTH_URL))
          OS_IDENTITY_API_VERSION: ((OS_IDENTITY_API_VERSION))
          OS_PROJECT_ID: ((OS_PROJECT_ID))
          OS_USER_DOMAIN_NAME: ((OS_USER_DOMAIN_NAME))
          OS_INTERFACE: ((OS_INTERFACE))
          OS_ENDPOINT_TYPE: ((OS_ENDPOINT_TYPE))
          OS_USERNAME: ((OS_USERNAME))
          OS_PASSWORD: ((OS_PASSWORD))
          OS_REGION_NAME: ((OS_REGION_NAME))
          OS_PROJECT_NAME: ((OS_PROJECT_NAME))

  - name: loadbalancer
    plan:
    - get: master
      trigger: true
    - task: automation test
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: imple/ansible-kitchen
        inputs:
          - name: master
        run:
          path: master/ci/scripts/test/loadbalancer.sh
        params:
          SSH_KEY: ((SSH_KEY))
          OS_AUTH_URL: ((OS_AUTH_URL))
          OS_IDENTITY_API_VERSION: ((OS_IDENTITY_API_VERSION))
          OS_PROJECT_ID: ((OS_PROJECT_ID))
          OS_USER_DOMAIN_NAME: ((OS_USER_DOMAIN_NAME))
          OS_INTERFACE: ((OS_INTERFACE))
          OS_ENDPOINT_TYPE: ((OS_ENDPOINT_TYPE))
          OS_USERNAME: ((OS_USERNAME))
          OS_PASSWORD: ((OS_PASSWORD))
          OS_REGION_NAME: ((OS_REGION_NAME))
          OS_PROJECT_NAME: ((OS_PROJECT_NAME))

  - name: Publish release
    plan:
    - get: master
      passed: [keystone, keystone-db, loadbalancer]
      trigger: true
    - put: version
      params:
        bump: minor
    - put: release
      params:
        name: version/version
        tag: version/version

  - name: Build images
    plan:
      - get: release
        trigger: true
      - get: master
      - task: Build keystone image
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: imple/packer
          inputs:
            - name: release
            - name: master
          run:
            path: master/ci/scripts/image/loadbalancer.sh
          params:
            SSH_KEY: ((SSH_KEY))
            OS_AUTH_URL: ((OS_AUTH_URL))
            OS_IDENTITY_API_VERSION: ((OS_IDENTITY_API_VERSION))
            OS_PROJECT_ID: ((OS_PROJECT_ID))
            OS_USER_DOMAIN_NAME: ((OS_USER_DOMAIN_NAME))
            OS_INTERFACE: ((OS_INTERFACE))
            OS_ENDPOINT_TYPE: ((OS_ENDPOINT_TYPE))
            OS_USERNAME: ((OS_USERNAME))
            OS_PASSWORD: ((OS_PASSWORD))
            OS_REGION_NAME: ((OS_REGION_NAME))
            OS_PROJECT_NAME: ((OS_PROJECT_NAME))
